"""Init

Revision ID: 3d363bb04b84
Revises: 9be6d4f3d2a8
Create Date: 2023-02-25 20:16:49.285395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d363bb04b84'
down_revision = '9be6d4f3d2a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
