"""Init

Revision ID: 9be6d4f3d2a8
Revises: 261d0da9d536
Create Date: 2023-02-25 20:16:29.575589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9be6d4f3d2a8'
down_revision = '261d0da9d536'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
